# Generated by Django 2.1.1 on 2018-09-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency1', models.TextField(max_length=3)),
                ('currency2', models.TextField(max_length=3)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
